spring.application.name=ecommerce-app

# Neon Database Connection
spring.datasource.url=jdbc:postgresql://ep-nameless-sun-b7rltpf8-pooler.c-13.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_IloGEk6r3QwV&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_IloGEk6r3QwV
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Settings (if using Spring Data JPA)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update